title: "xnlogic tutorials"
#author: "Blog Author"
description: "A collection of tutorials for the xnlogic framework."
#subheading: "Really cool blog about ... something"
more: "Go to the tutorial ..."
baseurl: "/getting_started" # comment out if in root directory

style:
    #body: "whitesmoke"
    padding: 25%
    anchor: "#46f"
    serif-heading: false
    nav: "#e7e7e7"
    #headline: "#a6f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/xnlogic/xnlogic"
  - xnlogic: "http://xnlogic.com"

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
