title: "xnlogic tutorials"
description: "A collection of tutorials for the xnlogic framework."
more: "Go to the tutorial ..."
baseurl: "/getting_started"

style:
    #body: "whitesmoke"
    padding: 25%
    anchor: "#46f"
    serif-heading: false
    nav: "#e7e7e7"
    #headline: "#a6f"
    description: "white"
    article:
        odd:  "#222222"
        even: "#ffffff"

links:
  - github: "https://github.com/xnlogic/xnlogic"
  - xnlogic: "http://xnlogic.com"

excerpt_separator: "\n\n\n"
defaults: [{scope: {path: ""}, values: {layout: "main"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
